### ISSUE TITLE
Base is unusable.

### ISSUE THREAD

**Issue by Boryte** [NikV2/AnticheatBase#8]
Without any checks this error pops up whenever a player attacks an entity.

[m[31;1m[19:07:59 ERROR]: [AntiCheatAddon] Unhandled exception occurred in onPacketReceiving(PacketEvent) for AntiCheatAddon
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.WrappedEnumEntityUseAction
	at com.comphenix.protocol.events.AbstractStructure.getEnumEntityUseActions(AbstractStructure.java:602) ~[?:?]
	at net.kyodo.anticheataddon.wrappers.WrapperPlayClientUseEntity.<init>(WrapperPlayClientUseEntity.java:27) ~[?:?]
	at net.kyodo.anticheataddon.processors.Packet.<init>(Packet.java:74) ~[?:?]
	at net.kyodo.anticheataddon.processors.listeners.NetworkListener.onPacketReceiving(NetworkListener.java:106) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) ~[?:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:549) ~[?:?]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:514) ~[?:?]
	at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:117) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:505) ~[?:?]
	at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) ~[?:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git-Carbon-"38757d2"]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:git-Carbon-"38757d2"]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
[m[31;1m[19:07:59 ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayInUseEntity@1ac37e6f[
    a=67
    action=ATTACK
    c=<null>
  ]

**Comment by NikV2** [comment]
use latest commit, its fixed

**Comment by NikV2** [comment]
and latest build dev from protocollib

**Comment by Boryte** [comment]
> and latest build dev from protocollib

I've used latest dev build and there is still the same error.

**Comment by NikV2** [comment]
with the latest commit that i just pushed? send me the error

**Comment by NikV2** [comment]
Should be fixed now, let me know
