### ISSUE TITLE
Still The same error when attacking entity

### ISSUE THREAD

**Issue by Anceaaa** [NikV2/AnticheatBase#9]
Hey Nik, i used latest ProtocolLib dev build and ur last commit but its still the same stuff.

[Ailey] Unhandled exception occurred in onPacketReceiving(PacketEvent) for Ailey
java.lang.ExceptionInInitializerError: null
        at com.comphenix.protocol.events.AbstractStructure.getEnumEntityUseActions(AbstractStructure.java:602) ~[ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at ac.ailey.wrappers.WrapperPlayClientUseEntity.<init>(WrapperPlayClientUseEntity.java:24) ~[Ailey.jar:?]
        at ac.ailey.processors.Packet.<init>(Packet.java:75) ~[Ailey.jar:?]
        at ac.ailey.processors.listeners.NetworkListener.onPacketReceiving(NetworkListener.java:108) ~[Ailey.jar:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeReceivingListener(SortedPacketListenerList.java:114) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketRecieving(SortedPacketListenerList.java:67) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at com.comphenix.protocol.injector.PacketFilterManager.postPacketToListeners(PacketFilterManager.java:549) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketReceiving(PacketFilterManager.java:514) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at com.comphenix.protocol.injector.netty.manager.NetworkManagerInjector.onPacketReceiving(NetworkManagerInjector.java:117) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at com.comphenix.protocol.injector.netty.channel.NettyChannelInjector.processInboundPacket(NettyChannelInjector.java:505) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at com.comphenix.protocol.injector.netty.channel.InboundPacketInterceptor.channelRead(InboundPacketInterceptor.java:33) [ProtocolLib.jar:5.0.0-SNAPSHOT-b614]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:163) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:150) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:787) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:430) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:384) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [s1.8.8.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: No constructor with [null] in class net.minecraft.server.v1_8_R3.PacketPlayInUseEntity
        at com.comphenix.protocol.wrappers.WrappedEnumEntityUseAction.useAction(WrappedEnumEntityUseAction.java:77) ~[?:?]
        at com.comphenix.protocol.wrappers.WrappedEnumEntityUseAction.<clinit>(WrappedEnumEntityUseAction.java:35) ~[?:?]
        ... 39 more
[20:55:33 ERROR]: Parameters:
  net.minecraft.server.v1_8_R3.PacketPlayInUseEntity@6eb749a2[
    a=106
    action=ATTACK
    c=<null>
  ]

**Comment by NikV2** [comment]
Should be fixed, let me know
